# Generated by Django 4.1.4 on 2022-12-08 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AttendanceData", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "InterviewAttendance", "managed": False,},
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "InterviewQuestion", "managed": False,},
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TheQuestion", models.CharField(max_length=150, unique=True)),
                ("Topic", models.CharField(max_length=50)),
                ("Type", models.CharField(max_length=50)),
                ("Level", models.CharField(max_length=15)),
                ("Visibility", models.CharField(max_length=15)),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Score", models.IntegerField(max_length=10)),
                ("Summary", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ReportWeakness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Weakness", models.CharField(max_length=255)),
                (
                    "ReportID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ServerDesign.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportStrengths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Strengths", models.CharField(max_length=255)),
                (
                    "ReportID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ServerDesign.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Answer", models.CharField(max_length=255)),
                (
                    "QuestionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ServerDesign.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
