# Generated by Django 4.1.4 on 2022-12-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='interviewID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.interview'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.question'),
        ),
    ]
