# Generated by Django 4.1.4 on 2023-01-28 20:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_interviewquestion_interviewid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastModified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='YP6AUTHTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optainedTime', models.DateTimeField(auto_now_add=True)),
                ('token', models.TextField()),
                ('expiry', models.DateTimeField(default=datetime.datetime(2023, 2, 4, 22, 2, 19, 363248))),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
