# Generated by Django 4.1.4 on 2023-01-28 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_user_lastmodified_alter_user_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yp6authtokens',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 22, 2, 47, 276493)),
        ),
    ]
