# Generated by Django 4.1.4 on 2023-01-29 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_yp6authtokens_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='yp6authtokens',
            name='macAddress',
            field=models.TextField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='yp6authtokens',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 19, 44, 0, 302644)),
        ),
        migrations.AlterField(
            model_name='yp6authtokens',
            name='token',
            field=models.TextField(default='None'),
        ),
    ]
