# Generated by Django 4.1.4 on 2023-01-29 18:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_yp6authtokens_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='yp6AuthenticationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macAddress', models.TextField(default='0.0.0.0', max_length=20)),
                ('optainedTime', models.DateTimeField(auto_now_add=True)),
                ('token', models.TextField(default='None', max_length=64)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2023, 2, 5, 20, 17, 42, 125754))),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='YP6AUTHTokens',
        ),
    ]
