# Generated by Django 4.1.4 on 2023-02-02 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0016_alter_yp6authenticationtoken_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dateOfBirth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 10, 1, 23, 56, 638575)
            ),
        ),
    ]
