# Generated by Django 4.1.4 on 2023-02-05 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_question', 'Can Create A Question'), ('can_create_interview', 'Can Create an Interview'), ('can_enter_interview', 'Can Enter Interview'), ('can_comment', 'Can Type Comments')]},
        ),
        migrations.AlterField(
            model_name='yp6authenticationtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 18, 43, 56, 302703)),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
