# Generated by Django 4.1.4 on 2023-02-09 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0020_alter_yp6authenticationtoken_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 16, 19, 58, 22, 78253)
            ),
        ),
    ]
