# Generated by Django 4.1.4 on 2023-03-25 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_alter_interview_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yp6authenticationtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 16, 1, 33, 965501)),
        ),
    ]
