# Generated by Django 4.1.4 on 2023-03-30 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_alter_yp6authenticationtoken_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yp6authenticationtoken',
            old_name='macAddress',
            new_name='signature',
        ),
        migrations.AlterField(
            model_name='yp6authenticationtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 0, 10, 57, 133095)),
        ),
    ]
