# Generated by Django 4.1.4 on 2023-03-30 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0025_alter_yp6authenticationtoken_expiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewattendance",
            name="reportID",
        ),
        migrations.AlterField(
            model_name="interviewattendance",
            name="duration",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 7, 0, 3, 11, 742263)
            ),
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
                (
                    "attendanceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.interviewattendance",
                    ),
                ),
                (
                    "questionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.question",
                    ),
                ),
            ],
        ),
    ]
