# Generated by Django 4.1.4 on 2023-03-30 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0026_remove_interviewattendance_reportid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewsession",
            name="answer",
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 7, 1, 29, 57, 20186)
            ),
        ),
    ]
