# Generated by Django 4.1.4 on 2023-03-31 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0028_interviewattendance_reportid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="answer",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 7, 5, 23, 28, 379316)
            ),
        ),
    ]
