# Generated by Django 4.1.4 on 2023-03-31 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0029_interviewsession_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 7, 13, 27, 35, 471073)
            ),
        ),
    ]
