# Generated by Django 4.1.4 on 2023-04-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0025_rename_macaddress_yp6authenticationtoken_signature_and_more"),
        ("server", "0032_alter_yp6authenticationtoken_expiry"),
    ]

    operations = []
