# Generated by Django 4.1.4 on 2023-04-10 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0033_merge_20230405_0731"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 17, 2, 31, 26, 929254)
            ),
        ),
    ]
