# Generated by Django 4.1.4 on 2023-04-11 18:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0034_user_job_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="isPrivate",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="password",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 18, 20, 55, 9, 304331)
            ),
        ),
        migrations.CreateModel(
            name="PrivateInterviewsUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expiryDate",
                    models.DateField(
                        default=datetime.datetime(2023, 4, 18, 20, 55, 9, 306362)
                    ),
                ),
                (
                    "interviewID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.interview",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
