# Generated by Django 4.1.4 on 2023-04-12 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0035_interview_isprivate_interview_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="password",
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="privateinterviewsusers",
            name="expiryDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 20, 0, 53, 58, 576563)
            ),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 20, 0, 53, 58, 574568)
            ),
        ),
    ]
