# Generated by Django 4.1.4 on 2023-04-19 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0036_alter_interview_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="graded",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="processed",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="videoPath",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="privateinterviewsusers",
            name="expiryDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 27, 1, 7, 20, 810054)
            ),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 1, 7, 20, 809057)
            ),
        ),
    ]
