# Generated by Django 4.1.4 on 2023-04-19 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0037_interviewsession_graded_interviewsession_processed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privateinterviewsusers",
            name="expiryDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 27, 1, 10, 9, 292556)
            ),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 1, 10, 9, 291559)
            ),
        ),
    ]
