# Generated by Django 4.1.4 on 2023-04-19 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0038_alter_privateinterviewsusers_expirydate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewsession",
            name="graded",
        ),
        migrations.RemoveField(
            model_name="interviewsession",
            name="processed",
        ),
        migrations.RemoveField(
            model_name="interviewsession",
            name="videoPath",
        ),
        migrations.AlterField(
            model_name="privateinterviewsusers",
            name="expiryDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 27, 1, 21, 0, 729422)
            ),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 1, 21, 0, 728425)
            ),
        ),
    ]
