# Generated by Django 4.1.4 on 2023-04-19 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0039_remove_interviewsession_graded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="grade",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="graded",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="processed",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="videoPath",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="privateinterviewsusers",
            name="expiryDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 27, 1, 46, 53, 930737)
            ),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 1, 46, 53, 928705)
            ),
        ),
    ]
