# Generated by Django 4.1.4 on 2023-04-20 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0042_alter_interviewsession_graded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewsession",
            name="graded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="videoPath",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="privateinterviewsusers",
            name="expiryDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 27, 2, 0, 48, 132961)
            ),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 2, 0, 48, 130966)
            ),
        ),
    ]
