# Generated by Django 4.1.4 on 2023-04-20 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0044_interviewsession_botresponse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewsession",
            name="botResponse",
        ),
        migrations.RemoveField(
            model_name="interviewsession",
            name="canTryAgain",
        ),
        migrations.AlterField(
            model_name="privateinterviewsusers",
            name="expiryDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 27, 3, 11, 37, 390233)
            ),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 3, 11, 37, 388236)
            ),
        ),
    ]
