# Generated by Django 4.1.4 on 2023-04-20 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0045_remove_interviewsession_botresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="botResponse",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="canTryAgain",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="privateinterviewsusers",
            name="expiryDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 27, 3, 15, 48, 368451)
            ),
        ),
        migrations.AlterField(
            model_name="yp6authenticationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 3, 15, 48, 367453)
            ),
        ),
    ]
