# Generated by Django 4.1.4 on 2023-04-26 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0049_alter_privateinterviewsusers_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinterviewsusers',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 23, 26, 37, 863168)),
        ),
        migrations.AlterField(
            model_name='yp6authenticationtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 23, 26, 37, 862171)),
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, null=True)),
                ('videoPath', models.TextField(default='')),
                ('grade', models.FloatField(default=0)),
                ('importantWords', models.TextField(null=True)),
                ('importantSentences', models.TextField(null=True)),
                ('angry', models.FloatField(default=0)),
                ('happy', models.FloatField(default=0)),
                ('disgust', models.FloatField(default=0)),
                ('fear', models.FloatField(default=0)),
                ('neutral', models.FloatField(default=0)),
                ('sad', models.FloatField(default=0)),
                ('surprise', models.FloatField(default=0)),
                ('status', models.CharField(default='Failed', max_length=6)),
                ('attendanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.interviewattendance')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.question')),
            ],
        ),
    ]
