# Generated by Django 4.1.4 on 2023-04-27 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0051_alter_privateinterviewsusers_expirydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='analysed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privateinterviewsusers',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 14, 43, 17, 446569)),
        ),
        migrations.AlterField(
            model_name='yp6authenticationtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 14, 43, 17, 444574)),
        ),
    ]
