# Generated by Django 4.1.4 on 2023-04-27 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0052_interviewresult_analysed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinterviewsusers',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 15, 25, 17, 618791)),
        ),
        migrations.AlterField(
            model_name='yp6authenticationtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 15, 25, 17, 617796)),
        ),
    ]
