# Generated by Django 4.1.4 on 2023-04-27 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0053_alter_privateinterviewsusers_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinterviewsusers',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 15, 26, 37, 718009)),
        ),
        migrations.AlterField(
            model_name='yp6authenticationtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 15, 26, 37, 716014)),
        ),
    ]
