# Generated by Django 4.1.4 on 2023-04-28 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0055_rename_importantsentences_interviewresult_intervieweeimportantsentences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.FloatField(default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='privateinterviewsusers',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 2, 2, 26, 868931)),
        ),
        migrations.AlterField(
            model_name='yp6authenticationtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 2, 2, 26, 867934)),
        ),
    ]
