# Generated by Django 4.1.3 on 2022-12-17 01:24

from django.db import migrations, models
import djongo.models.fields
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview", models.TextField()),
                ("startDate", models.DateTimeField(auto_now_add=True)),
                ("endDate", models.DateTimeField(auto_now=True)),
                ("report", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                (
                    "userCreated",
                    djongo.models.fields.EmbeddedField(
                        model_container=server.models.User
                    ),
                ),
                (
                    "questions",
                    djongo.models.fields.ArrayField(
                        model_container=server.models.Question
                    ),
                ),
                ("date", models.DateTimeField()),
                ("password", models.TextField()),
                ("permission", models.CharField(max_length=10)),
                (
                    "allowedUsers",
                    djongo.models.fields.ArrayField(model_container=server.models.User),
                ),
                (
                    "attendances",
                    djongo.models.fields.ArrayField(model_container=server.models.User),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.TextField()),
                ("topic", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                ("visibility", models.CharField(max_length=50)),
                ("answer", models.TextField()),
                (
                    "userCreated",
                    djongo.models.fields.EmbeddedField(
                        model_container=server.models.User
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.FloatField()),
                ("summary", models.TextField()),
                (
                    "weaknesses",
                    djongo.models.fields.ArrayField(
                        model_container=server.models.Weakness
                    ),
                ),
                (
                    "strengths",
                    djongo.models.fields.ArrayField(
                        model_container=server.models.Strength
                    ),
                ),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Strength",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("strength", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("accountType", models.CharField(max_length=50)),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("dateOfBirth", models.DateTimeField()),
                ("password", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Weakness",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("weakness", models.CharField(max_length=50)),
            ],
        ),
    ]
